# Librerías de Python

La librerías y paquetes de Python son un conjunto de módulos y funciones. Actualmente hay cientos de miles de librerías y paquetes de Python listos para ser utilizados por los desarrolladores para implementar soluciones modernas a diferentes problemas.

Algunas definiciones:
-   **Módulo** : Código de Python contenido en un archivo.
-   **Paquete**: Código de Python contenido en un directorio de archivos. Dicho directorio debe contener al menos un archivo **init.py**
-   **Librería**: Colección de módulos y paquetes de Python

# Introducción a la librería  NumPy

NumPy es una librería fundamental para la computación científica en Python. Contiene:
-  Clases para trabajar con vectores y matrices multidimensionales
-  Colección de rutinas matemáticas de alto nivel para manejar vectores y matrices
-  Herramientas de integración con código de C/C++ y Fortran
-  Utilidades para algebra lineal , Transformada de Fourier y números aleatorios, funciones estadísticas y trigonométricas entre otros

La documentación oficial de la librería se puede encontrar en: **numpy.org**

Un buen tutorial https://www.tutorialspoint.com/numpy/index.htm

## Aplicaciones
-  Operaciones relacionadas con álgebra lineal
-  Ciencia de datos y aprendizaje máquina (tensores)
-  Procesamiento de imágenes.
-  Se dice que puede ser reemplazo de Matlab

##  Arreglos con NumPy

El manejo de arreglos con NumPy es mucho más rápido que el uso de listas porque:
-  Usa menos bytes en memoria.
-  Usa memoria contigua.
-  Tiene muchas más funciones 

Diferencia: Lista es redimensionable y puede ser heterogenea

In [1]:
#importar la librería
import numpy as np

###  Creación de arreglos homogeneos (del mismo tipo)

Numpy soporta diferentes tipos https://docs.scipy.org/doc/numpy/user/basics.types.html

In [28]:
#vector
v=np.array([10,20,30,40])
#Matriz
m=np.array([[1.0,3.0,5.0], [2.0,4.0,5.0]])
print("vector ",v)
print("matriz ",m)

vector  [10 20 30 40]
matriz  [[1. 3. 5.]
 [2. 4. 5.]]


In [143]:
v1=np.array([10,20,30,40], dtype=np.int8)
print('tamaño v1:',v1.nbytes)
print('tamaño v:',v.nbytes)

tamaño v1: 4
tamaño v: 16


In [18]:
#convierte todos al mismo tipo
c=np.array([10,'a',30,40])

In [20]:
print(c)

['10' 'a' '30' '40']


#### Ejercicio 1.
Crea e imprime un arreglo de tres dimensiones

In [ ]:
#crea e imprime un arreglo de tres dimensiones


In [44]:
#inicializar con zeros
ceros=np.zeros((4,5))
ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
#inicializar con unos 
unos=np.ones((4,5,3))
unos

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
#inicializar con otro numero
otro=np.full((3,3),100)
otro

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [48]:
#inicializar con matriz identidad
identidad=np.identity(5)
identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
#inicializar con aleatorios reales
aleatReal=np.random.rand(4,3)
aleatReal

array([[0.85603807, 0.84744871, 0.25517611],
       [0.44011561, 0.29566426, 0.44980941],
       [0.19029548, 0.7562043 , 0.66046991],
       [0.47075526, 0.73161349, 0.18335562]])

In [51]:
#inicializar con aleatorios enteros
aleatEntero=np.random.randint(1,10, size=(4,3))
aleatEntero

array([[3, 9, 8],
       [6, 1, 8],
       [9, 3, 6],
       [9, 6, 1]])

In [88]:
#inicializar a partir de una lista
lista=[2,4,6,8,10,12,14,16]
#l1=np.array([lista])
l=np.array([lista]).reshape(4,2)
l

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [164]:
#inicializa a partir de un rango y determina las dimensiones
x=np.arange(2,200,10).reshape(4,5)
x

array([[  2,  12,  22,  32,  42],
       [ 52,  62,  72,  82,  92],
       [102, 112, 122, 132, 142],
       [152, 162, 172, 182, 192]])

In [ ]:
#leer datos y crear una matriz  
#asarray convierte secuencias en ndarray
lista=[]
for i in range(3):
    for j in range(4):
        aij=int(input('elemento:' ))
        lista.append(aij)
matriz=np.asarray(lista).reshape(3,4)
matriz

#### Slicing

In [165]:
x[1:3,2:]  #semejante a listas

array([[ 72,  82,  92],
       [122, 132, 142]])

### **Ejercicios:**
    2. Crea una matriz de 5x5 asi:
       1  1  1  1  1
       1  0  0  0  1
       1  0  5  0  1
       1  0  0  0  1
       1  1  1  1  1
       
    3. Crea una matriz con los multiplos de 5 de 5 a 40 asi:
       5  10  15  20
       25 30  35  40

###  Atributos básicos
-  **ndim**.-  Número de dimensiones o ejes del arreglo
-  **shape**.- Dimensiones del arreglo
-  **size**.-  Total de elementos de un arreglo
-  **dtype**.- Tipo de los elementos del arreglo

In [12]:
#ndim
print("Numero de dimensiones de v ", v.ndim)
print("Numero de dimensiones de m ", m.ndim)

Numero de dimensiones de v  1
Numero de dimensiones de m  2


In [13]:
#shape
print("Dimensiones de v ", v.shape)
print("Dimensiones de m ", m.shape)

Dimensiones de v  (4,)
Dimensiones de m  (2, 3)


In [14]:
#size
print("Total de elementos de v ", v.size)
print("Total de elementos de m ", m.size)

Total de elementos de v  4
Total de elementos de m  6


In [29]:
#Tipo
print(m.dtype)
print(v.dtype)

float64
int32


In [26]:
#en general se usa menos frecuentemente array con cadenas
x=np.array(['a','b','c'],dtype=str)
print(x.dtype)

<U1


In [ ]:
#NumPy tiene muchos elementos útiles
dir(np)

## Operaciones con arreglos

### Acceder a elementos

In [58]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#aceder a un elemento
a[1,3]

9

In [33]:
#acceder a un renglón
a[1:]  # como slice

array([[ 6,  7,  8,  9, 10]])

In [35]:
#acceder a una columna
a[:,3]

array([4, 9])

In [37]:
#slice similar al for   [start:end:step]
a[1,1:4:2]  #el renglon 1 empieza en el elemento 1 hasta el 4 e incrementa de dos en dos

array([7, 9])

In [39]:
#cambiar valores
#un valor
a[1,1]=1000
print(a)

[[   1    2    3    4    5]
 [   6 1000    8    9   10]]


In [42]:
#cambiar un renglón
a[0,]=50
print(a)

[[50 50 50 50 50]
 [ 6  7  8  9 10]]


In [43]:
#cambiar una columna
a[:,3]=2000
print(a)

[[  50   50   50 2000   50]
 [   6    7    8 2000   10]]


### Copiar arreglos

In [91]:
r1=np.random.randint(9, size=(3,3))
r2=np.random.randint(9, size=(3,3))
print(r1)
print(r2)

[[8 4 5]
 [7 2 3]
 [4 4 1]]
[[0 1 7]
 [7 4 4]
 [7 7 8]]


In [92]:
#si asigno un arreglo a otro solo apuntan los dos al mismo arreglo
otro=r1
otro[1,1]=1000
print(otro)
print(r1)

[[   8    4    5]
 [   7 1000    3]
 [   4    4    1]]
[[   8    4    5]
 [   7 1000    3]
 [   4    4    1]]


In [93]:
#con copy realmente se hace una copia del arreglo
otro=np.copy(r2)
print(otro)
print(r2)

[[0 1 7]
 [7 4 4]
 [7 7 8]]
[[0 1 7]
 [7 4 4]
 [7 7 8]]


In [94]:
otro[1,1]=1000
print(otro)
print(r2)

[[   0    1    7]
 [   7 1000    4]
 [   7    7    8]]
[[0 1 7]
 [7 4 4]
 [7 7 8]]


#### Concatenar arreglos

In [120]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#print(a)
#print(b)
#de manera vertical 
print(np.vstack((a,b)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [118]:
#de manera horizontal 
print(np.hstack((a,b)))

[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


### Operaciones sencillas por elemento

In [95]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a=a+2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

*Probar la resta, multiplicación y division*

In [66]:
#suma de matrices
a=np.array([[1,2],[3,4]])
b=np.array([[1,3],[4,5]])

In [71]:
a+b

array([[2, 5],
       [7, 9]])

In [169]:
#también existe add, substract, multiply, divide
uno=np.arange(9).reshape(3,3)
dieces=np.array([10,10,10])
print('uno ',uno)
print('dieces',dieces)
print(np.add(uno,dieces))

uno  [[0 1 2]
 [3 4 5]
 [6 7 8]]
dieces [10 10 10]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


Sumar columnas,  renglones o todos los elementos de una matriz

In [106]:
#Sumar todos los elementos
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
suma=np.sum(a)
suma

55

In [110]:
#axis=0 se refiere a las columnas y axis=1 se refiere a los renglones
#Sumar renglones  
sumaren=np.sum(a, axis=1)
sumaren

array([15, 40])

**Ejercicios**
  4.  Calcula la suma de columnas
  5.  ¿Cómo imprimo solo la suma de una columna en particular?

###  Algebra lineal - Multiplicación de matrices

In [72]:
np.dot(a,b)

array([[ 9, 13],
       [19, 29]])

In [73]:
np.matmul(a,b)

array([[ 9, 13],
       [19, 29]])

In [74]:
a@b

array([[ 9, 13],
       [19, 29]])

In [75]:
a@np.identity(2)

array([[1., 2.],
       [3., 4.]])

In [175]:
#Matriz inversa
A=[[1,3],[2,4]]
AI=np.linalg.inv(A)
AI

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [176]:
#verifico que si es la inversa
A@AI

array([[1., 0.],
       [0., 1.]])

6. ¿Cuál es la diferencia entre a@b y a*b  ?

###  Otras operaciones con matrices

In [98]:
#Sacar la matriz transpuesta
x=np.arange(0,90,10).reshape(3,3)
x
t=np.transpose(x)
print(x)
print(t)

[[  2  12  22  32  42]
 [ 52  62  72  82  92]
 [102 112 122 132 142]
 [152 162 172 182 192]]
[[  2  52 102 152]
 [ 12  62 112 162]
 [ 22  72 122 172]
 [ 32  82 132 182]
 [ 42  92 142 192]]


In [96]:
#extrae la diagonal
np.diag(t)

array([  2,  62, 122, 182])

In [102]:
#ordenar un arreglo
aleat=np.random.randint(20, size=(25))
aleat

array([16,  3, 14,  9, 13, 18, 13,  7, 15,  1,  2,  0,  9, 11,  5, 10,  8,
       18, 14, 19, 19,  3,  5, 18,  6])

In [104]:
aleat=np.sort(aleat)
aleat

array([ 0,  1,  2,  3,  3,  5,  5,  6,  7,  8,  9,  9, 10, 11, 13, 13, 14,
       14, 15, 16, 18, 18, 18, 19, 19])

###  Funciones estadísticas

In [124]:
#Algunas estadísticas básicas
A=np.random.randint(20, size=(25))
print(A)
print("Media",np.mean(A))
print("Mediana",np.median(A))
print("Desviación estandar",np.std(A))
print("Varianza",np.var(A))
print("Promedio",np.average(A))
print("Mínimo",np.amin(A))
print("Máximo",np.amax(A))

[12 16  8 10  7 13 13  3 15  4 13 11  5 17 16 10  2  5 16 10 16 14 19  1
  0]
Media 10.24
Mediana 11.0
Desviación estandar 5.4352920804681695
Varianza 29.5424
Promedio 10.24
Mínimo 0
Máximo 19


In [125]:
#Menor por columna
a=np.array([[1,2,3,4,5],[6,7,2,9,1]])
print(np.amin(a, axis=0))

[1 2 2 4 1]


###  Funciones trigonométricas

In [178]:
#seno de 90 grados (1)
np.sin(np.pi/2)

0.7071067811865476

In [186]:
import matplotlib.pylab as plt
x=np.linspace(-np.pi,np.pi*3,700)
plt.plot(x,np.sin(x))
plt.xlabel=('Angulo en radianes')
plt.ylabel=('Seno de x')
plt.axis('tight') #que se ajuste al tamaño
plt.show()

##  Ejercicios con NumPy para análisis de datos

### 1. Extraer los datos que satisfagan una condición por ejemplo los mayores a 5000

In [128]:
#Genera las ventas de 10 vendedores por 12 meses
ventas=np.random.randint(0,10001, size=(10,12))
ventas

array([[2119, 3629, 5942, 8627, 3305, 4992, 7166, 9746, 9993, 1935, 8847,
        4923],
       [6601, 5650, 8313, 3047, 2344, 4757, 6389,  370, 7279,  878, 1308,
        9707],
       [7972, 2756, 6212, 1613, 8602, 6274, 9587, 2848, 4071, 9541, 5995,
        1853],
       [4516, 9135, 3921, 5893,  984, 1896, 9952, 5634, 1537, 2153, 6553,
        1139],
       [4439, 7183, 2673, 2246, 2208, 7017, 4951, 4618, 2877, 4059, 7950,
        1372],
       [5246, 4309, 9491, 9278, 7786, 3154, 1000,  806, 8601, 7707,  519,
        4516],
       [ 368, 7906,   38, 6311,  931, 4965, 6203,  421, 4248, 1345, 8520,
        3661],
       [5816, 3474, 6769, 3175, 7295,  667, 9561, 3231, 7770, 5656, 3458,
        8123],
       [9829, 3392, 4472, 7783, 2253, 9395, 6226, 9732, 3948,  544, 8888,
        1256],
       [1903, 7751,  994, 9711, 3238,  902, 7939, 2970, 4198, 4355,  801,
        8843]])

In [132]:
res=ventas>5000
res

array([[False, False,  True,  True, False, False,  True,  True,  True,
        False,  True, False],
       [ True,  True,  True, False, False, False,  True, False,  True,
        False, False,  True],
       [ True, False,  True, False,  True,  True,  True, False, False,
         True,  True, False],
       [False,  True, False,  True, False, False,  True,  True, False,
        False,  True, False],
       [False,  True, False, False, False,  True, False, False, False,
        False,  True, False],
       [ True, False,  True,  True,  True, False, False, False,  True,
         True, False, False],
       [False,  True, False,  True, False, False,  True, False, False,
        False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True, False,  True],
       [ True, False, False,  True, False,  True,  True,  True, False,
        False,  True, False],
       [False,  True, False,  True, False, False,  True, False, False,
        False, False

In [134]:
may5000=np.extract(res,ventas)  #en un paso may5000=np.extract(ventas>5000,ventas)
may5000

array([1935,  370,  878, 1308, 1613, 1853,  984, 1896, 1537, 1139, 1372,
       1000,  806,  519,  368,   38,  931,  421, 1345,  667,  544, 1256,
       1903,  994,  902,  801])

**Ejercicios:**
    -  Extrae las ventas menores a 2000
    -  Extrae las ventas mayores al promedio

### 2. Reemplaza los elementos que satisfagan una condición por ejemplo los negativos por 0

In [136]:
# Genera edades algunas con errores
edades=np.random.randint(-30,120, size=(30))
edades

array([ 59,  20, 105,  12,  76, 106, -11, 104,  24, 116,  24, -28,  16,
        63,  42,  61,  16,  23,   1,  92,  45,  64,  -9,  24,  69,  32,
        54,   7,  -4,   5])

In [137]:
edadesN=np.where(edades<0,0,edades)
edadesN

array([ 59,  20, 105,  12,  76, 106,   0, 104,  24, 116,  24,   0,  16,
        63,  42,  61,  16,  23,   1,  92,  45,  64,   0,  24,  69,  32,
        54,   7,   0,   5])

**Ejercicio:** reemplaza los negativos por la media

Revisar uso de NumPy para procesar imágenes
https://note.nkmk.me/en/python-numpy-image-processing/

## Soluciones de los ejercicios

In [144]:
# 1.Crea e imprime un arreglo de tres dimensiones
tres=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tres)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [158]:
# 2. Crea una matriz de 5x5 asi:
#      1  1  1  1  1
#      1  0  0  0  1
#      1  0  5  0  1
#      1  0  0  0  1
#      1  1  1  1  1
mat=np.ones((5,5))
mat[1:4,1:4]=0
mat[2,2]=5
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 5., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
#3. Crea una matriz con los multiplos de 5 de 5 a 40 asi:
#   5  10  15  20
#   25 30  35  40
cincos=np.arange(5,45,5).reshape(2,4)
cincos

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [170]:
#4. Calcula la suma de columnas
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
sumacol=np.sum(a, axis=0)
sumacol

array([ 7,  9, 11, 13, 15])

In [171]:
#5. ¿Cómo imprimo solo la suma de una columna en particular?
sumacol[3]

13

In [172]:
#6. ¿Cuál es la diferencia entre a@b y a*b  ?
a=np.array([[1,2],[3,4]])
b=np.array([[1,3],[4,5]])
print(a@b) #multiplicación de matrices
print(a*b) #multiplicación de elementos


[[ 9 13]
 [19 29]]
[[ 1  6]
 [12 20]]


**Tarea:**
 Ir pensando proyecto final: seleccionar una o dos librerías de Python que sean relevantes para un problema, explicar las librerías en ese contexto y cómo se podrán aplicar a un problema propuesto.
    